"""
ScholarMind — Upload Parquet to Supabase + Build BM25 Index

This script takes the parquet file generated by the Kaggle notebook
and does two things:
1. Uploads all papers (with embeddings) to your Supabase database.
2. Builds a BM25 index from the text data and saves it to disk.

Usage:
    python -m ingestion.upload_to_supabase --file path/to/scholarmind_papers_with_embeddings.parquet
"""

import argparse
import json
import pickle
import re
import time
from pathlib import Path

import numpy as np
import pandas as pd
# pyrefly: ignore [missing-import]
from rank_bm25 import BM25Okapi
from supabase import create_client

# ============================================================
# Configuration — set these or use command-line args
# ============================================================
DEFAULT_PARQUET = "data/scholarmind_papers_with_embeddings.parquet"
BM25_OUTPUT = "data/bm25_index.pkl"
BATCH_SIZE = 500  # rows per Supabase insert call


def tokenize(text: str) -> list[str]:
    """Simple whitespace + lowercase tokenizer."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s\-]", " ", text)
    tokens = text.split()
    return [t for t in tokens if len(t) > 1]


def upload_to_supabase(df: pd.DataFrame, supabase_url: str, supabase_key: str):
    """Upload papers to the Supabase papers table in batches."""
    client = create_client(supabase_url, supabase_key)

    total = len(df)
    uploaded = 0
    failed = 0

    print(f"\nUploading {total:,} papers to Supabase in batches of {BATCH_SIZE}...")

    for start in range(0, total, BATCH_SIZE):
        batch_df = df.iloc[start : start + BATCH_SIZE]
        batch = []

        for _, row in batch_df.iterrows():
            # Parse JSON string columns back to lists
            authors = json.loads(row["authors"]) if isinstance(row["authors"], str) else row["authors"]
            categories = json.loads(row["categories"]) if isinstance(row["categories"], str) else row["categories"]
            all_cats = json.loads(row["all_categories"]) if isinstance(row["all_categories"], str) else row["all_categories"]

            # Embedding: convert from list/array to list of floats
            embedding = row["embedding"]
            if isinstance(embedding, str):
                embedding = json.loads(embedding)
            if isinstance(embedding, np.ndarray):
                embedding = embedding.tolist()

            batch.append(
                {
                    "paper_id": str(row["paper_id"]),
                    "title": str(row["title"]),
                    "abstract": str(row["abstract"]),
                    "authors": authors,
                    "categories": categories,
                    "all_categories": all_cats,
                    "published_at": str(row["published_at"]),
                    "year": int(row["year"]),
                    "embedding": embedding,
                }
            )

        try:
            # Upsert to handle potential duplicates
            client.table("papers").upsert(batch, on_conflict="paper_id").execute()
            uploaded += len(batch)
        except Exception as e:
            failed += len(batch)
            print(f"  ❌ Batch at row {start} failed: {e}")

        # Progress
        pct = (start + len(batch)) / total * 100
        print(f"  [{pct:5.1f}%] Uploaded {uploaded:,} / {total:,} (failed: {failed})", end="\r")

    print(f"\n✅ Upload complete: {uploaded:,} uploaded, {failed} failed")


def build_bm25_index(df: pd.DataFrame, output_path: str):
    """Build a BM25 index from paper titles + abstracts and save to disk."""
    print(f"\nBuilding BM25 index for {len(df):,} papers...")

    paper_ids = []
    paper_metadata = []
    tokenized_corpus = []

    for _, row in df.iterrows():
        text = f"{row['title']} {row['abstract']}"
        tokens = tokenize(text)

        paper_ids.append(row["paper_id"])
        tokenized_corpus.append(tokens)

        # Parse JSON string columns back to lists
        authors = json.loads(row["authors"]) if isinstance(row["authors"], str) else row["authors"]
        categories = json.loads(row["categories"]) if isinstance(row["categories"], str) else row["categories"]

        paper_metadata.append(
            {
                "paper_id": str(row["paper_id"]),
                "title": str(row["title"]),
                "abstract": str(row["abstract"]),
                "authors": authors,
                "categories": categories,
                "year": int(row["year"]),
            }
        )

    # Build BM25
    bm25 = BM25Okapi(tokenized_corpus)

    # Save to disk
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "wb") as f:
        pickle.dump(
            {
                "bm25": bm25,
                "paper_ids": paper_ids,
                "paper_metadata": paper_metadata,
            },
            f,
        )

    file_size_mb = Path(output_path).stat().st_size / (1024 * 1024)
    print(f"✅ BM25 index saved to {output_path} ({file_size_mb:.1f} MB)")


def main():
    parser = argparse.ArgumentParser(description="Upload ScholarMind data to Supabase")
    parser.add_argument("--file", type=str, default=DEFAULT_PARQUET, help="Path to parquet file")
    parser.add_argument("--supabase-url", type=str, required=True, help="Supabase project URL")
    parser.add_argument("--supabase-key", type=str, required=True, help="Supabase service role key")
    parser.add_argument("--bm25-output", type=str, default=BM25_OUTPUT, help="BM25 index output path")
    parser.add_argument("--skip-upload", action="store_true", help="Skip Supabase upload, only build BM25")
    parser.add_argument("--skip-bm25", action="store_true", help="Skip BM25 build, only upload")
    args = parser.parse_args()

    # Load parquet
    print(f"Loading parquet from {args.file}...")
    t0 = time.time()
    df = pd.read_parquet(args.file)
    print(f"Loaded {len(df):,} papers in {time.time() - t0:.1f}s")
    print(f"Columns: {list(df.columns)}")

    # Upload to Supabase
    if not args.skip_upload:
        upload_to_supabase(df, args.supabase_url, args.supabase_key)

    # Build BM25 index
    if not args.skip_bm25:
        build_bm25_index(df, args.bm25_output)

    print("\n🎉 All done!")


if __name__ == "__main__":
    main()
